spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"



  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://configserver:8071/}"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eurekaserver:8070/eureka/}
    fetch-registry: true
    register-with-eureka: true



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Testcase Generator Gateway Server Application"
    version: "1.0.0"


logging:
  level:
    com:
      tefal:
        gatewayserver: DEBUG


